org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

modId=structurize
modGroup=com.ldtteam
local.version=0.0.1-local
modBaseName=structurize

javaVersion=25
useJavaToolChains=true

# Minecraft and NeoForge
minecraft.version=26.2
minecraft.additionalVersions=
neoforge.version=26.2.0.66

fml_range=[11,)
neoforge_range=[26.2,)
minecraft_range=[26.2, 27)
blockUiRange=[0.0.1,)
domumOrnamentumRange=[1.0.0,)

usesMCVersionOrderFirst=true

githubUrl=https://github.com/ldtteam/Structurize
gitUrl=https://github.com/ldtteam/Structurize.git
gitConnectUrl=https://github.com/ldtteam/Structurize.git
projectUrl=https://www.curseforge.com/minecraft/mc-mods/Structurize

curseId=298744
usesCurse=true

usesCrowdin=false
crowdinId=structurize

requiredCurseDependencies=domum-ornamentum;blockui

useDefaultTestSystem=true
runtimeSourceSets=api;test;main
librarySourceSets=api;test;main;datagen;
projectHasApi=true
primaryJarClassifier=
usesSonarQube=false
