package com.ldtteam.structurize.generation;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.ldtteam.datagenerators.IJsonSerializable;
import com.ldtteam.structurize.api.util.constant.Constants;

public class DataGeneratorConstants
{

    public static final Gson GSON     = new GsonBuilder().disableHtmlEscaping().create();

    private static final String DATAPACK_DIR = "data/" + Constants.MOD_ID + "/";

    // DataPack Directories \\

    public static final String LOOT_TABLES_DIR = DATAPACK_DIR + "loot_tables/blocks";

    /**
     * Utility method to add a "message" to the json objects before writing.
     *
     * @param serializable the serializable
     * @return the new jsonElement
     */
    public static JsonElement serialize(IJsonSerializable serializable)
    {
        return serialize(serializable.serialize());
    }

    public static JsonElement serialize(JsonElement serialized)
    {
        if (serialized.isJsonObject())
            serialized.getAsJsonObject().addProperty("READ ME!!!", "DO NOT EDIT THIS FILE. DON'T TOUCH IT, TOUCH IT AND YOU WILL REGRET IT ~~ AshersLab (Use the Data Generators!)");
        return serialized;
    }
}
