repositories {
    mavenLocal()
}

dependencies {
    apiImplementation "com.ldtteam:blockui:0.0.1-local"
    implementation "com.ldtteam:blockui:0.0.1-local"

    apiImplementation "com.ldtteam:domum-ornamentum:1.0.0-local"
    implementation "com.ldtteam:domum-ornamentum:1.0.0-local"
    runtimeOnly "com.ldtteam:domum-ornamentum:1.0.0-local"

    testImplementation 'junit:junit:4.13.2'
}
